// source https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_web_frameworks

export let javascriptWebFrameworks = [
  'Angular',
  'AngularJS',
  'Royale',
  'Backbone.js',
  'Dojo',
  'Ember.js',
  'Enyo',
  // 'Ext JS',
  'Google Web Toolkit',
  'jQuery',
  'jQWidgets',
  'Knockout',
  'MooTools',
  // 'Prototype',
  'qooxdoo',
  'React',
  'OpenUI5',
  'SolidJS',
  'SproutCore',
  'Svelte',
  'Vue.js',
  'Wakanda',
  'Webix',
  'ZK',
  'XMLHttpRequest',
  'WebSocket',
  'Angular',
  'AngularJS',
  'Royale',
  'Dojo',
  'Ember.js',
  'Enyo',
  // 'Ext JS',
  'Google Web Toolkit',
  'jQuery',
  'jQWidgets',
  'MooTools',
  // 'Prototype',
  'qooxdoo',
  'React',
  'OpenUI5',
  'SproutCore',
  'Svelte',
  'Vue',
  'Wakanda',
  'ZK',
  'Webix',
  '.NET',
  'C++',
  'ColdFusion',
  'Common Lisp',
  'Haskell',
  'Java',
  'JavaScript',
  'Perl',
  'PHP',
  'Python',
  'Ruby',
  'Rust',
  'Scala',
  'Smalltalk',
  'ECMAScript',
  'JavaScript',
  'Unit test',
]
